#!/bin/sh
#
# Run a series of test cases through the driver one at a time
# using the testAfl tool.
#
set -x
testfile=$1

AFL=${TAFL:-/TriforceAFL/}
KERN=$3

/TriforceLinuxSyscallFuzzer/testAfl $AFL/$9 \
    -kernel $KERN -drive $4  \
    -m 256M -nographic -append "root=/dev/$5 fdyne_execute=0 firmadyne.devfs=0 firmadyne.procfs=0 rw init=/init console=${10} mem=256M" \
    -M $8 \
    -trace_module 0 \
    -aflPanicAddr $6  \
    ${11} -aflFile2 $testfile \
    -aflFile @@ -- "$2" 
